### ISSUE TITLE
Error while building caffe with GPU support

### ISSUE THREAD

**Issue by kv55** [inisis/caffe#1]
The following error occurred while building caffe with GPU support (USE_CUDNN := 1)
**Makefile:588: recipe for target '.build_release/cuda/src/caffe/layers/proposal_layer.o' failed**
-------------------------------------------------------------
complete error log below

NVCC src/caffe/layers/proposal_layer.cu
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/proposal_layer.cu:240:185:   required from here
src/caffe/layers/proposal_layer.cu:240:185: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                         ^
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/proposal_layer.cu:240:188:   required from here
src/caffe/layers/proposal_layer.cu:240:188: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                            ^
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/proposal_layer.cu:240:185:   required from here
src/caffe/layers/proposal_layer.cu:240:185: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                         ^
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/proposal_layer.cu:240:188:   required from here
src/caffe/layers/proposal_layer.cu:240:188: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                            ^
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/proposal_layer.cu:240:185:   required from here
src/caffe/layers/proposal_layer.cu:240:185: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                         ^
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/proposal_layer.cu:240:188:   required from here
src/caffe/layers/proposal_layer.cu:240:188: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                            ^
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/proposal_layer.cu:240:185:   required from here
src/caffe/layers/proposal_layer.cu:240:185: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                         ^
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/proposal_layer.cu:240:188:   required from here
src/caffe/layers/proposal_layer.cu:240:188: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                            ^
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/proposal_layer.cu:240:185:   required from here
src/caffe/layers/proposal_layer.cu:240:185: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                         ^
src/caffe/layers/proposal_layer.cu: In instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/proposal_layer.cu:240:188:   required from here
src/caffe/layers/proposal_layer.cu:240:188: error: explicit instantiation of ‘void caffe::ProposalLayer<Dtype>::Backward_gpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<bool>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’ but no definition available [-fpermissive]
 INSTANTIATE_LAYER_GPU_FUNCS(ProposalLayer);
                                                                                                                                                                                            ^
Makefile:588: recipe for target '.build_release/cuda/src/caffe/layers/proposal_layer.o' failed
make: *** [.build_release/cuda/src/caffe/layers/proposal_layer.o] Error 1

**Comment by inisis** [comment]
Hi, currently, only cpu is supported.
